name: docker
on: push

jobs:
  push-docker:
    strategy:
      fail-fast: false
      matrix:
        include:
          - dialect: mysql:latest
          - dialect: mysql:5.6
            platforms: linux/amd64
          - dialect: mysql:5.6.35
            platforms: linux/amd64
          - dialect: mysql:5.7
            platforms: linux/amd64
          - dialect: mysql:5.7.26
            platforms: linux/amd64
          - dialect: mysql:8
          - dialect: mariadb:latest
            build-args: SERVER=mariadbd
          - dialect: mariadb:10.2
          - dialect: mariadb:10.2.32
          - dialect: mariadb:10.3
          - dialect: mariadb:10.3.13
          - dialect: mariadb:10.7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build & Push ${{ matrix.dialect }} Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./.github/ops/mysql/Dockerfile
          tags: arigaio/${{ matrix.dialect }}
          # platforms: ${{ matrix.platforms || 'linux/amd64,linux/arm64' }}
          provenance: false
          build-args: |
            DIALECT=${{ matrix.dialect }}
            ${{ matrix.build-args }}
